### ISSUE TITLE
Add toggle for "chat" type.

### ISSUE THREAD

**Issue by NoltoxGit** [Smudgge/Leaf#110]
Hello,
Is it possible to add a command for toggle staffchat mode please ?

For example i've this:
```
staff_chat:
  type: "chat"
  enabled: true
  name: "staffchat"
  aliases: [ "sc" ]
  permission: "leaf.staffchat"
  format: "&8[&#e64545&l{server_formatted}&8]&r &6<player>&r &7» &#73a1e6>%message%"
  receive_sound: "BLOCK_NOTE_BLOCK_XYLOPHONE"
  sound: "BLOCK_NOTE_BLOCK_XYLOPHONE"
```

And it's possible to add a /sctoggle command in this section which will have the option of forcing writing in this chat or not.
